### ISSUE TITLE
Two missing _DHE_ cipher suites

### ISSUE THREAD

**Issue by emanjon** [tlswg/draft-deprecate-obsolete-kex#8]
The following 2 cipher suites are not mentioned in Appendix A. Probably because of their weird names.

TLS_PSK_DHE_WITH_AES_128_CCM_8
TLS_PSK_DHE_WITH_AES_256_CCM_8

**Comment by nimia** [comment]
Are those TLS 1.2 cipher suites, or TLS 1.3 ones? The document does not depreate TLS 1.3 FFDHE.

**Comment by emanjon** [comment]
They are TLS 1.2 cipher suites. TLS 1.3 cipher suites does not have PSK or DHE in their names. They were registered by RFC 6655 way before TLS 1.3 existed. You probably missed them as all the other DHE cipher suites are beginning with TLS_DHE_ such as TLS_DHE_PSK_WITH_AES_128_CCM

**Comment by nimia** [comment]
Ah, right. Fixed this, thanks!
I'd like to thank you in the acknowledgements section, just making sure that the spelling on your GitHub profile is correct - John Preuß Mattsson ?

**Comment by emanjon** [comment]
Thanks. That's correct. You need to put in three angle braces to make the unicode work in markdown {{{John Preuß Mattsson}}} but the ASCII version "John Preuss Mattsson" is also ok.

**Comment by nimia** [comment]
Duly acknowledged :-) thanks!
